      SUBROUTINE RPTIN (NUNIT,NBUF,LOCRPT,NWDS,JJ,KLMAX,JEOF)
      SAVE
C***
C***    READS PHYSICAL BLOCKS; AND UNBLOCKS ONE LOGICAL RECORD
C***    FOR EACH CALL
C***
C TO READ RPTOUT RECORDS WRITTEN ON A MACHINE OF WORD LENGTH $LIN$ BITS IN TO
C A MACHINE OF WORD LENGTH $LOT$ BITS    - BUFFER LENGTH IN IS IMAX
C LOT WORDS - IE LARGE ENOUGH FOR THE BUFFER SIZE IN LIN BIT WORDS
C ALL LENGTHS IN THE CALLING SEQUENCE ARE $LOT$ BIT WORDS
C NCAR    2 JUL 71     D JOSEPH
      DIMENSION NBUF(1),LOCRPT(1)
C
C FOR CDC750
C     DATA IMAX/1073/
C     DATA KMAX/1067/
C     DATA LIN/64/
C     DATA LOT/60/
C
C FOR 32 machines
      DATA IMAX/2006/
      DATA KMAX/2000/
      DATA LIN/64/
      DATA LOT/32/
C
      COMMON/IND/LOT
      IF (NBUF(1) .EQ. 0) GO TO 3
      IF (NBUF(1) .NE. 7) GO TO 40
      GO TO 6
    3 CALL IOWAIT(NUNIT,NBUF(6),NWRED)
      XL=LOT
      XF=LIN
      XF=XL/XF
      YF=1./XF
      ID=LIN-LOT
      LII=7
      LGET=LIN
      LOFF=0
C     LGET=60
C     LOFF=4
      IF (LOT .GE. LIN) GO TO 4
      LOFF=ID
      LGET=LOT
      XOFF=LOFF
      XP=XOFF/XL
      IP=XP
      LOFF=(XP-IP)*XL+.01
      LII=IP+7
    4 CONTINUE
    5 CALL RDTAPE(NUNIT,1,2,NBUF(7),KMAX)
    6 CALL IOWAIT(NUNIT,NBUF(6),NWRED)
      IBITS=LIN
      NBUF(1)=8
      JEOF=NBUF(6)
      IF (JEOF .EQ. 1) GO TO 42
      NTST=XF*NWRED+.01
      IF (NTST .GT. 2) GO TO 10
      IEREC=NBUF(3)+1
      PRINT 960,NUNIT,IEREC,NWRED,NBUF(6)
  960 FORMAT(' +++ RPTINX SHORT PHYS REC,UNIT,PHYS REC,EXP LTH ',4I8)
   10 NBUF(5)=NWRED
      CALL GBYTES(NBUF(LII),IWDS,LOFF,LGET,0,1)
      NWU=(XF*NWRED)+0.01
      NWL=NWU-XF+.99
      IF (IWDS .GE. NWL .AND. IWDS .LE. NWU) GO TO 18
      IEREC=NBUF(3)+1
      PRINT 962,NUNIT,IEREC,NWRED,IWDS,NBUF(6)
  962 FORMAT(' +++ RPTINX - BAD PHYS LTH,UNIT,PHYS REC , LTH, EXP LTH,
     2 STATUS',5I8)
      GO TO 5
   18 CONTINUE
      NBUF(6)=0
      NBUF(3)=NBUF(3)+1
      NBUF(4)=NBUF(4)+NWRED
      LBITS=LIN*(IWDS-1)
   40 JEOF=NBUF(6)
      XBITS=IBITS
      XP=XBITS/XL
      IP=XP
      IOF=(XP-IP)*XL+.01
      II=IP+1
      CALL GBYTES(NBUF(II+6),NWDS,IOF,12,0,1)
      IF (NWDS .GT. 0 .AND. NWDS .LT.(IWDS-2)) GO TO 46
      IEREC=NBUF(2)+1
      PRINT 964,NUNIT,IEREC,NWDS
  964 FORMAT(' +++ RPTINX- BAD LOGICAL LENGTH,UNIT,LOG REC,LTH ',5I8)
      GO TO 3
   46 CONTINUE
      LTH=XF*NWDS+.99
      IBITS=IBITS+LIN*NWDS
      NWDS=YF*NWDS+.99
      CALL GBYTES(NBUF(II+6),LOCRPT,IOF,LOT,0,NWDS)
      NBUF(2)=NBUF(2)+1
      NBUF(1)=NBUF(1)+NWDS
      IF (IBITS .GE. LBITS) GO TO 52
      RETURN
   52 NBUF(1)=7
      CALL RDTAPE(NUNIT,1,2,NBUF(7),KMAX)
   42 CONTINUE
      RETURN
      END

