	PROGRAM VAXREC
C
	BYTE      IBUF(12000),IPADD(3)
	CHARACTER FILENAME*40
C
	DATA IPADD/3*0/
C
	IREC=0
	JREC=0
C
	WRITE(*,*) 'ENTER INPUT FILE NAME: '
	READ(*,10) FILENAME
10	FORMAT(A40)
	WRITE(*,*) 'ENTER RECORD LENGTH (**BYTES**) OF OUTPUT FILE: '
	READ(*,*) NRECL
	NWDS=(NRECL+3)/4
	OPEN(UNIT=1,FILE=FILENAME,STATUS='OLD',FORM='UNFORMATTED',
     +ACCESS='SEQUENTIAL')
	OPEN(UNIT=2,FILE=FILENAME,STATUS='NEW',FORM='UNFORMATTED',
     +ACCESS='DIRECT',RECL=NWDS)
C
C fill buffer with enough bytes to write one output record
	IBEG=1
15	CONTINUE
	DO 20 I=IBEG,NRECL,512
	  IEND=IBEG+511
	  READ(1,END=998) (IBUF(J),J=IBEG,IEND)
	  IREC=IREC+1
	  IBEG=IBEG+512
20	CONTINUE
C
C write the output record and position buffer for next read
	WRITE(2,REC=JREC+1) (IBUF(J),J=1,NRECL),
     +(IPADD(J),J=NRECL+1,NWDS*4)
	JREC=JREC+1
	JJ=1
	DO 30 I=NRECL+1,IEND
	  IBUF(JJ)=IBUF(I)
	  JJ=JJ+1
30	CONTINUE
	IBEG=JJ
	IEND=IBEG+511
	GOTO 15
C
998	CONTINUE
	CLOSE(1,STATUS='KEEP')
	CLOSE(2,STATUS='KEEP')
	WRITE(*,1001) IREC,NRECL,JREC
1001	FORMAT(1X,'NUMBER OF 512-BYTE VAX RECORDS READ: ',i8,/,
     +1x,'NUMBER OF ',i5,'-BYTE RECORDS WRITTEN: ',i7)
	END
